spring:
    datasource:
      url: jdbc:postgresql://localhost/postgres
      username : karthik
      password : karthikr1234
    jpa:
      hibernate:
        ddl-auto : none
      show-sql :  true
      properties:
        hibernate:
          format_sql : true
    servlet:
      multipart:
        max-file-size: 1MB

server:
  tomcat:
    max-swallow-size: 50MB

      